version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=efootweardb
      - DB_USER=postgres
      - DB_PASS=ultrasecretpassword
    depends_on:
      - db
      - minio

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key
    command: server /minio-data --console-address ":9001"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=efootweardb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ultrasecretpassword
      
